language: java
jdk:
- openjdk11
brances:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
before_install:
- openssl aes-256-cbc -K $encrypted_c1ad7a6a264d_key -iv $encrypted_c1ad7a6a264d_iv
  -in gyunny.tar.enc -out ./src/main/resources/gyunny.tar -d
