language: java
jdk:
- openjdk11
brances:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
before_install:
- openssl aes-256-cbc -K $encrypted_99eda7ed15ec_key -iv $encrypted_99eda7ed15ec_iv
  -in src/main/resources/gyunny.tar.enc -out src/main/resources/gyunny.tar -d
